version: "3"

services:
  jenkins-master-service:
    build: ./master
    image: rapid_value_jenkins:0.1
    container_name: rapidvalue-jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_network
    env_file: ./master/env.list
    volumes:
      - jenkins_home:/var/jenkins_home
#      - ./master/data:/var/jenkins_home
#    volumes:
      # Path on the host, relative to the Compose file using SHORT SYNTAX
#      - ./master/jobs:/var/jenkins_home/jobs
#  jenkins-slave-service:
#    build: ./slave
#    image: rapid_value_jenkins_slave:0.1
#    container_name: rapidvalue-jenkins-slave
#    depends_on:
#      - jenkins-master-service
#    networks:
#      - jenkins_network
#    command: -url http://localhost:8080 secret123 agent123

networks:
  jenkins_network:
volumes:
   jenkins_home: